/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void changePlants(GCustomSlider source, GEvent event) { //_CODE_:plantSlider:575540:
  numPlants = plantSlider.getValueI();
  createPlants();
} //_CODE_:plantSlider:575540:

public void pauseResume(GButton source, GEvent event) { //_CODE_:pause:517437:
  paused = !paused;
  if(pause.getText() == "pause"){
    pause.setText("resume");
    pause.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  }else{
    pause.setText("pause");
    pause.setLocalColorScheme(GCScheme.RED_SCHEME);
  }
} //_CODE_:pause:517437:


// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  plantSlider = new GCustomSlider(this, 50, 0, 100, 40, "grey_blue");
  plantSlider.setLimits(20, 0, 50);
  plantSlider.setNbrTicks(50);
  plantSlider.setNumberFormat(G4P.INTEGER, 0);
  plantSlider.setOpaque(false);
  plantSlider.addEventHandler(this, "changePlants");
  plantLabel = new GLabel(this, 60, 30, 80, 20);
  plantLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  plantLabel.setText("plants");
  plantLabel.setOpaque(false);
  pause = new GButton(this, 475, 15, 100, 40);
  pause.setText("pause");
  pause.setLocalColorScheme(GCScheme.RED_SCHEME);
  pause.addEventHandler(this, "pauseResume");
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider plantSlider; 
GLabel plantLabel; 
GButton pause;